version: '3'
services:

  movies_db:
    image: postgres:15-alpine
    volumes:
      - ../postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_user}
      POSTGRES_DB: ${db_name}
      PG_DATA: /var/lib/postgresql/base
    container_name: movies_db
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"


  movies_admin:
    build:
      context: ./.
    env_file:
      - ./config/.env
    container_name: movies_admin
    depends_on:
      - movies_db
    ports:
      - "8000:8000"

